window.AbrahamContentTranslations = {
  'Xe đạp 12 inch': ['12-inch Bikes', '12英寸自行车'],
  'Xe đạp 14 inch': ['14-inch Bikes', '14英寸自行车'],
  'Xe đạp 16 inch': ['16-inch Bikes', '16英寸自行车'],
  'Xe đạp 18 inch': ['18-inch Bikes', '18英寸自行车'],
  'Xe đạp 20 inch': ['20-inch Bikes', '20英寸自行车'],
  '(2-4 tuổi)': ['(2-4 years)', '(2-4 岁)'],
  '(3-5 tuổi)': ['(3-5 years)', '(3-5 岁)'],
  '(4-6 tuổi)': ['(4-6 years)', '(4-6 岁)'],
  '(5-7 tuổi)': ['(5-7 years)', '(5-7 岁)'],
  '(6-9 tuổi)': ['(6-9 years)', '(6-9 岁)'],
  'Đi đến nội dung chính': ['Skip to content', '跳转到主要内容'],
  'Tìm kiếm sản phẩm': ['Search products', '搜索产品'],
  'Tìm kiếm sản phẩm…': ['Search products…', '搜索产品…'],
  'Mở menu': ['Open menu', '打开菜单'],
  'Đăng nhập để quản lý tài khoản và đơn hàng của bạn.': ['Sign in to manage your account and orders.', '登录以管理您的账户和订单。'],
  'ABRAHAM BIKE · HƠN 20 NĂM ĐỒNG HÀNH': ['ABRAHAM BIKE · OVER 20 YEARS BY YOUR SIDE', 'ABRAHAM BIKE · 陪伴您超过20年'],
  'Đồng hành cùng': ['By your side for a', '陪伴您走向'],
  'tương lai khỏe mạnh': ['healthier future', '健康的未来'],
  'tương lai khỏe mạnh.': ['healthier future.', '健康的未来。'],
  'Abraham Bike – Đồng hành cùng': ['Abraham Bike – By your side for a', 'Abraham Bike – 陪伴您走向'],
  'Xe đạp cho trẻ em – Gia đình – Thể thao – Thành phố': ['Bikes for children – Families – Sports – City riding', '儿童 – 家庭 – 运动 – 城市自行车'],
  'Khám phá xe đạp': ['Explore bikes', '探索自行车'],
  'Tìm đại lý gần bạn': ['Find a dealer near you', '查找附近经销商'],
  '20+ năm': ['20+ years', '20多年'],
  'Kinh nghiệm đồng hành cùng': ['Experience serving', '服务经验'],
  'hàng triệu gia đình Việt': ['millions of Vietnamese families', '数百万越南家庭'],
  '3.000+ đại lý': ['3,000+ dealers', '3,000多家经销商'],
  'Toàn quốc': ['Nationwide', '全国'],
  'Chuẩn CR': ['CR standard', 'CR标准'],
  'Sản phẩm đạt tiêu chuẩn': ['Products meeting', '产品符合'],
  'chất lượng': ['quality standards', '质量标准'],
  'Bảo hành chính hãng': ['Manufacturer warranty', '原厂保修'],
  'Hỗ trợ nhanh chóng': ['Prompt support', '及时支持'],
  'trên toàn quốc': ['nationwide', '覆盖全国'],
  'DANH MỤC SẢN PHẨM': ['PRODUCT CATEGORIES', '产品分类'],
  'Mỗi người một chiếc xe phù hợp': ['The right bike for everyone', '每个人都能找到合适的自行车'],
  'Khám phá các dòng xe đạp Abraham với thiết kế đa dạng,': ['Explore Abraham’s wide range of bicycle designs,', '探索Abraham多样化的自行车设计，'],
  'phù hợp mọi độ tuổi và nhu cầu sử dụng.': ['suited to every age and riding need.', '满足各年龄段和骑行需求。'],
  'Xem tất cả danh mục →': ['View all categories →', '查看所有分类 →'],
  'Xe đạp trẻ em': ['Children’s bikes', '儿童自行车'],
  'Cho bé từ 2 – 12 tuổi': ['For children aged 2–12', '适合2至12岁儿童'],
  'Xe đạp nữ': ['Women’s bikes', '女士自行车'],
  'Đi học, đi làm, dạo phố': ['School, work and city rides', '上学、通勤和城市骑行'],
  'Xe đạp MTB': ['Mountain bikes', '山地自行车'],
  'Thể thao & địa hình': ['Sports & off-road riding', '运动与越野骑行'],
  'Đường dài & khám phá': ['Long-distance rides & exploration', '长途骑行与探索'],
  'Gọn nhẹ cho đô thị': ['Compact for city living', '适合城市生活的轻巧设计'],
  'SẢN PHẨM NỔI BẬT': ['FEATURED PRODUCTS', '精选产品'],
  'Những mẫu xe được yêu thích nhất': ['Our most popular bikes', '最受欢迎的自行车'],
  'Thiết kế đẹp, bền bỉ và phù hợp': ['Attractive, durable designs tailored', '美观、耐用的设计，满足'],
  'với nhu cầu của từng thành viên trong gia đình.': ['to every family member’s needs.', '每位家庭成员的需求。'],
  'Đang tải sản phẩm…': ['Loading products…', '正在加载产品…'],
  'VÌ SAO CHỌN ABRAHAM?': ['WHY CHOOSE ABRAHAM?', '为什么选择ABRAHAM？'],
  'Ba điều chúng tôi': ['Three values', '我们坚持的'],
  'giữ vững': ['we uphold', '三项价值'],
  'Chúng tôi luôn nỗ lực mang đến những sản phẩm chất lượng và dịch vụ tốt nhất, đồng hành cùng bạn trên mọi hành trình.': ['We strive to provide quality products and excellent service, supporting you on every journey.', '我们致力于提供优质产品和出色服务，陪伴您的每一次旅程。'],
  'Thông tin sản phẩm rõ ràng, minh bạch, đúng giá trị thật.': ['Clear, transparent product information and honest value.', '清晰透明的产品信息，体现真实价值。'],
  'Hơn 20 năm đồng hành cùng hàng triệu gia đình Việt.': ['Over 20 years serving millions of Vietnamese families.', '服务数百万越南家庭超过20年。'],
  'Hỗ trợ trước, trong và sau khi mua xe, luôn đặt khách hàng làm trung tâm.': ['Customer-focused support before, during and after your purchase.', '以客户为中心，提供购车前、中、后的支持。'],
  'THƯƠNG HIỆU VIỆT · HƠN 20 NĂM PHÁT TRIỂN': ['VIETNAMESE BRAND · OVER 20 YEARS OF GROWTH', '越南品牌 · 发展超过20年'],
  'Abraham luôn kiên định với sứ mệnh mang đến những chiếc xe đạp chất lượng, an toàn và phù hợp với người Việt. Chúng tôi không ngừng cải tiến, ứng dụng công nghệ và lắng nghe khách hàng để tạo ra những sản phẩm tốt hơn mỗi ngày.': ['Abraham is committed to providing quality, safe bicycles suited to Vietnamese riders. We continuously improve, adopt technology and listen to customers to make better products every day.', 'Abraham致力于为越南骑行者提供优质、安全、合适的自行车。我们持续改进、应用技术并倾听客户意见，每天打造更好的产品。'],
  'Thiết kế phù hợp': ['Thoughtful design', '贴心设计'],
  'Thị hiếu Việt': ['For Vietnamese riders', '适合越南骑行者'],
  'Đa dạng mẫu mã': ['Wide model selection', '多样款式'],
  'Cho mọi nhu cầu': ['For every need', '满足各种需求'],
  'Chất lượng tiêu chuẩn': ['Quality standards', '质量标准'],
  'An toàn · Bền bỉ': ['Safe · Durable', '安全 · 耐用'],
  'Trên toàn quốc': ['Nationwide', '覆盖全国'],
  'HỆ THỐNG ĐẠI LÝ': ['DEALER NETWORK', '经销商网络'],
  '3.000+ đại lý,': ['3,000+ dealers,', '3,000多家经销商，'],
  'luôn gần bạn': ['always close to you', '始终在您身边'],
  'Tìm đại lý Abraham gần nhất để trải nghiệm': ['Visit your nearest Abraham dealer to explore', '前往附近的Abraham经销商体验'],
  'sản phẩm và nhận tư vấn trực tiếp.': ['our products and get personal advice.', '产品并获得现场咨询。'],
  'Tỉnh/Thành phố': ['Province/City', '省份/城市'],
  'Tìm đại lý': ['Find a dealer', '查找经销商'],
  'Ghé thăm Abraham': ['Visit Abraham', '到访Abraham'],
  'Khám phá cửa hàng xe đạp Abraham quanh bạn.': ['Discover Abraham bicycle stores near you.', '探索您附近的Abraham自行车门店。'],
  'Mở Google Maps ↗': ['Open Google Maps ↗', '打开Google地图 ↗'],
  'Liên hệ tư vấn →': ['Contact us for advice →', '联系我们获取建议 →'],
  'Chọn khu vực để tìm kiếm trên bản đồ.': ['Choose an area to search on the map.', '选择区域以在地图上搜索。'],
  'KIẾN THỨC & TƯ VẤN': ['GUIDES & ADVICE', '知识与建议'],
  'Góc đạp xe cùng Abraham': ['Cycling with Abraham', '与Abraham一起骑行'],
  'Những bài viết hữu ích giúp bạn lựa chọn, sử dụng và bảo dưỡng xe đạp đúng cách.': ['Helpful articles on choosing, riding and maintaining your bicycle.', '实用文章助您正确选择、使用和保养自行车。'],
  'Xem tất cả bài viết →': ['View all articles →', '查看所有文章 →'],
  'Cách chọn xe đạp cho bé theo độ tuổi và chiều cao': ['Choosing a child’s bike by age and height', '根据年龄和身高选择儿童自行车'],
  'Khám phá bài viết': ['Read article', '阅读文章'],
  'Hướng dẫn bảo dưỡng xe đạp tại nhà trong 10 phút': ['A 10-minute guide to bicycle maintenance at home', '10分钟居家自行车保养指南'],
  'Xe đạp nữ nên chọn loại nào để đi học, đi làm?': ['Which women’s bike is best for school or work?', '上学或通勤应选择哪种女士自行车？'],
  'Hỗ trợ': ['Support', '支持'],
  'Bảo hành': ['Warranty', '保修'],
  'Hướng dẫn sử dụng': ['User guides', '使用指南'],
  'Về Abraham': ['About Abraham', '关于Abraham'],
  'Giới thiệu': ['About us', '品牌介绍'],
  'Tin tức': ['News', '新闻'],
  'Giá trị thương hiệu': ['Brand values', '品牌价值'],
  'Tư vấn sản phẩm & hỗ trợ': ['Product advice & support', '产品咨询与支持'],
  'Xem chi tiết': ['View details', '查看详情'],
  'Xem chi tiết →': ['View details →', '查看详情 →'],
  'Còn hàng': ['In stock', '有货'],
  'Hết hàng': ['Out of stock', '缺货'],
  'Chọn màu': ['Choose a color', '选择颜色'],
  'Thêm vào giỏ hàng': ['Add to cart', '加入购物车'],
  'Mua ngay': ['Buy now', '立即购买'],
  'Mô tả sản phẩm': ['Product description', '产品描述'],
  'Thông số kỹ thuật': ['Specifications', '技术规格'],
  'Sản phẩm liên quan': ['Related products', '相关产品'],
  'Những chiếc xe đạp chất lượng': ['Quality bicycles', '优质自行车'],
  'cho thế hệ năng động hơn.': ['for a more active generation.', '为更有活力的一代。'],
  'Bảo hành & hỗ trợ': ['Warranty & support', '保修与支持'],
  'Tư vấn sản phẩm': ['Product advice', '产品咨询'],
  'Liên hệ Abraham →': ['Contact Abraham →', '联系Abraham →'],
  'Danh mục': ['Categories', '分类'],
  'Tất cả': ['All', '全部'],
  'Đăng ký': ['Sign up', '注册'],
  'Chưa có tài khoản?': ['Don’t have an account?', '还没有账户？'],
  'Xe đạp': ['Bicycles', '自行车']
};

window.AbrahamCartTranslations = {
  'Account Password': ['Mật khẩu tài khoản', '账户密码'],
  'Please fill in your information to complete the order': ['Vui lòng điền thông tin để hoàn tất đơn hàng', '请填写信息以完成订单'],
  'Enter your coupon code to get a discount': ['Nhập mã giảm giá để nhận ưu đãi', '输入优惠码以享受折扣'],
  'Enter your coupon code if you have one': ['Nhập mã giảm giá nếu bạn có', '如有优惠码，请输入'],
  'Coupon Code': ['Mã giảm giá', '优惠码'],
  'Street address': ['Địa chỉ đường, số nhà', '街道地址及门牌号'],
  'Apartment, suite, unit etc. (optional)': ['Căn hộ, tầng, phòng… (không bắt buộc)', '公寓、楼层、房间等（选填）'],
  'Phone Number': ['Số điện thoại', '电话号码'],
  'Write your notes here...': ['Nhập ghi chú của bạn…', '请填写备注……'],
  'Review your selected products': ['Kiểm tra sản phẩm đã chọn', '核对已选商品'],
  'Posta / Zip': ['Mã bưu chính', '邮政编码'],
  'Vietnam': ['Việt Nam', '越南'],
  'Select a country': ['Chọn quốc gia', '选择国家'],
  'bangladesh': ['Bangladesh', '孟加拉国'],
  'Algeria': ['Algérie', '阿尔及利亚'],
  'Afghanistan': ['Afghanistan', '阿富汗'],
  'Ghana': ['Ghana', '加纳'],
  'Albania': ['Albania', '阿尔巴尼亚'],
  'Bahrain': ['Bahrain', '巴林'],
  'Colombia': ['Colombia', '哥伦比亚'],
  'Dominican Republic': ['Cộng hòa Dominica', '多米尼加共和国'],
  'Create an account by entering the information below. If you are a returning customer please login at the top of the page.': ['Điền thông tin bên dưới để tạo tài khoản. Nếu đã có tài khoản, vui lòng đăng nhập ở đầu trang.', '填写以下信息以创建账户。如果已有账户，请在页面顶部登录。'],
  'Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order won’t be shipped until the funds have cleared in our account.': ['Chuyển khoản trực tiếp vào tài khoản ngân hàng của chúng tôi và ghi mã đơn hàng trong nội dung chuyển khoản. Đơn hàng sẽ được giao sau khi chúng tôi nhận được thanh toán.', '请直接转账至我们的银行账户，并在转账备注中填写订单号。我们收到付款后将安排发货。'],
  'Your cart is empty.': ['Giỏ hàng của bạn đang trống.', '您的购物车是空的。'],
  'Please complete all required delivery information correctly.': ['Vui lòng điền đầy đủ và chính xác thông tin giao hàng bắt buộc.', '请正确填写所有必填的配送信息。'],
  'Please log in before placing your order.': ['Vui lòng đăng nhập trước khi đặt hàng.', '请先登录再下单。'],
  'Placing order...': ['Đang đặt hàng…', '正在提交订单……'],
  'The order was not saved.': ['Đơn hàng chưa được lưu.', '订单未保存。'],
  'Unable to save your order. Please try again.': ['Không thể lưu đơn hàng. Vui lòng thử lại.', '无法保存订单，请重试。'],
  'Shopping cart': ['Giỏ hàng', '购物车'],
  'Proceed to checkout': ['Tiến hành thanh toán', '去结算'],
  'A few steps closer to your next adventure.': ['Chỉ còn vài bước để bắt đầu hành trình mới của bạn.', '距离您的下一次冒险又近了几步。'],
  'Quantities and totals update automatically.': ['Số lượng và tổng tiền được cập nhật tự động.', '数量和总金额会自动更新。'],
  'Enter your delivery address and confirm your order in the next step.': ['Nhập địa chỉ giao hàng và xác nhận đơn hàng ở bước tiếp theo.', '请在下一步输入收货地址并确认订单。'],
  'We’re here to help you choose your ride.': ['Chúng tôi luôn sẵn sàng giúp bạn chọn chiếc xe phù hợp.', '我们随时帮助您选择合适的自行车。'],
  'LET’S FIND YOUR RIDE': ['TÌM CHIẾC XE CỦA BẠN', '寻找您的自行车'],
  'Explore our collection and add a bike you love.': ['Khám phá bộ sưu tập và thêm chiếc xe bạn yêu thích vào giỏ hàng.', '浏览我们的系列，将喜欢的自行车加入购物车。'],
  'Unit price:': ['Đơn giá:', '单价：'],
  'Item total:': ['Thành tiền:', '商品总价：'],
  'Removed from your cart.': ['Đã xóa sản phẩm khỏi giỏ hàng.', '已从购物车移除。']
};

window.AbrahamShopTranslations = {
  'Categories': ['Danh mục', '分类'],
  'Availability': ['Tình trạng hàng', '库存状态'],
  'Price range': ['Khoảng giá', '价格范围'],
  'Min': ['Tối thiểu', '最低'],
  'Max': ['Tối đa', '最高'],
  'Apply filters': ['Áp dụng bộ lọc', '应用筛选'],
  'Reset filters': ['Đặt lại bộ lọc', '重置筛选'],
  'Sort by:': ['Sắp xếp theo:', '排序方式：'],
  'Newest': ['Mới nhất', '最新'],
  'Price: low to high': ['Giá: thấp đến cao', '价格：从低到高'],
  'Price: high to low': ['Giá: cao đến thấp', '价格：从高到低'],
  'Name: A–Z': ['Tên: A–Z', '名称：A–Z'],
  'products': ['sản phẩm', '件商品'],
  'Bikes': ['Xe đạp', '自行车'],
  'Bicycle Parts': ['Phụ tùng xe đạp', '自行车配件'],
  'E-bike Parts': ['Phụ tùng xe đạp điện', '电动自行车配件'],
  'Controller Parts': ['Phụ tùng bộ điều khiển', '控制器配件'],
  'Electric Bikes': ['Xe đạp điện', '电动自行车'],
  'View details': ['Xem chi tiết', '查看详情'],
  'Add to cart': ['Thêm vào giỏ hàng', '加入购物车'],
  'In stock': ['Còn hàng', '有货'],
  'Out of stock': ['Hết hàng', '缺货'],
  'No products found': ['Không tìm thấy sản phẩm', '未找到产品'],
  'Try a different search or adjust your filters.': ['Thử từ khóa khác hoặc điều chỉnh bộ lọc.', '请尝试其他关键词或调整筛选条件。'],
  'Loading products...': ['Đang tải sản phẩm...', '正在加载产品…'],
  'Unable to load products': ['Không thể tải sản phẩm', '无法加载产品'],
  'Check your connection and try again.': ['Kiểm tra kết nối và thử lại.', '请检查网络连接后重试。'],
  'Try again': ['Thử lại', '重试'],
  'Enter a valid price range. Max must be at least Min.': ['Nhập khoảng giá hợp lệ. Giá tối đa phải lớn hơn hoặc bằng giá tối thiểu.', '请输入有效价格范围，最高价不能低于最低价。'],
  'Unable to save favorites in this browser.': ['Không thể lưu sản phẩm yêu thích trong trình duyệt này.', '无法在此浏览器中保存收藏。'],
  'Grid view': ['Hiển thị dạng lưới', '网格视图'],
  'List view': ['Hiển thị dạng danh sách', '列表视图'],
  'Product layout': ['Bố cục sản phẩm', '产品布局'],
  'Product pagination': ['Phân trang sản phẩm', '产品分页'],
  'Product filters': ['Bộ lọc sản phẩm', '产品筛选'],
  'Product categories': ['Danh mục sản phẩm', '产品分类'],
  'Previous page': ['Trang trước', '上一页'],
  'Next page': ['Trang sau', '下一页'],
  'Add to favorites': ['Thêm vào yêu thích', '加入收藏'],
  'Remove from favorites': ['Bỏ khỏi yêu thích', '取消收藏']
};
