const fs = require('node:fs'), path = require('node:path'), vm = require('node:vm'), assert = require('node:assert/strict');
function run(native) {
    const handlers = {}, items = new Map();
    const element = () => ({ src: '', textContent: '', attrs: {}, dataset: {}, classList: { add() {}, toggle() {} }, setAttribute(k, v) { this.attrs[k] = v; }, getAttribute(k) { return this.attrs[k]; } });
    const texts = ['Trang chủ', 'Sản phẩm', 'Kiến thức', 'Xe đạp trẻ em', 'Sort by:', 'Apply filters', 'Xe đạp 12 inch', '(2-4 tuổi)', '4 màu'].map(value => ({ nodeValue: value, parentElement: { closest() { return null; } } }));
    const picker = { ...element(), querySelector(s) { if (!items.has(s)) items.set(s, element()); return items.get(s); }, querySelectorAll() { return []; }, addEventListener(k, fn) { handlers[k] = fn; } };
    const actions = { querySelector() { return {}; }, insertBefore() {} };
    const body = { querySelectorAll() { return []; } };
    const window = { localStorage: { getItem() { return 'vi'; }, setItem() {} }, addEventListener(k, fn) { handlers[k] = fn; } };
    const document = { body, documentElement: {}, querySelector(s) { return s === '#language-picker' ? (native ? picker : null) : actions; }, getElementById() { return null; }, createElement() { return picker; }, querySelectorAll() { return []; }, createTreeWalker() { let i = 0; return { nextNode() { return texts[i++] || null; } }; } };
    const context = vm.createContext({ document, window, NodeFilter: { SHOW_TEXT: 4 }, MutationObserver: class { observe() {} } });
    vm.runInContext(fs.readFileSync(path.join(__dirname, '../js/language-content.js'), 'utf8'), context);
    vm.runInContext(fs.readFileSync(path.join(__dirname, '../js/language.js'), 'utf8'), context);
    handlers.click({ target: { closest() { return { getAttribute() { return 'en'; } }; } } });
    assert.deepEqual(texts.map(t => t.nodeValue), ['Home', 'Products', 'Knowledge', 'Children’s bikes', 'Sort by:', 'Apply filters', '12-inch Bikes', '(2-4 years)', '4 colors']);
    handlers['abraham-language-change']({ detail: { language: 'zh' } });
    assert.equal(texts[0].nodeValue, '首页');
    assert.equal(texts[4].nodeValue, '排序方式：');
    assert.equal(texts[7].nodeValue, '(2-4 岁)');
    handlers['abraham-language-change']({ detail: { language: 'vi' } });
    assert.equal(texts[0].nodeValue, 'Trang chủ');
    assert.equal(texts[1].nodeValue, 'Sản phẩm');
    assert.equal(texts[4].nodeValue, 'Sắp xếp theo:');
    assert.equal(texts[5].nodeValue, 'Áp dụng bộ lọc');
    assert.equal(texts[8].nodeValue, '4 màu');
    const checkout = { nodeValue: 'Proceed to checkout', parentElement: { closest() { return null; } } };
    const count = { nodeValue: '1 item', parentElement: { closest() { return null; } } };
    texts.push(checkout, count);
    handlers['abraham-language-change']({ detail: { language: 'vi' } });
    assert.equal(checkout.nodeValue, 'Tiến hành thanh toán');
    assert.equal(count.nodeValue, '1 sản phẩm');
    handlers['abraham-language-change']({ detail: { language: 'zh' } });
    assert.equal(checkout.nodeValue, '去结算');
    assert.equal(count.nodeValue, '1 件商品');
    handlers['abraham-language-change']({ detail: { language: 'en' } });
    assert.equal(checkout.nodeValue, 'Proceed to checkout');
    assert.equal(count.nodeValue, '1 item');
    const checkoutLabels = ['Enter your coupon code if you have one', 'Street address', 'Phone Number', 'Quantity: 2'].map(nodeValue => ({ nodeValue, parentElement: { closest() { return null; } } }));
    texts.push(...checkoutLabels);
    handlers['abraham-language-change']({ detail: { language: 'vi' } });
    assert.deepEqual(checkoutLabels.map(t => t.nodeValue), ['Nhập mã giảm giá nếu bạn có', 'Địa chỉ đường, số nhà', 'Số điện thoại', 'Số lượng: 2']);
    handlers['abraham-language-change']({ detail: { language: 'zh' } });
    assert.deepEqual(checkoutLabels.map(t => t.nodeValue), ['如有优惠码，请输入', '街道地址及门牌号', '电话号码', '数量：2']);
    handlers['abraham-language-change']({ detail: { language: 'en' } });
    assert.equal(checkoutLabels[0].nodeValue, 'Enter your coupon code if you have one');
}
run(true); run(false);
console.log('Passed VI/EN/ZH switching and restoration on both header types.');
